name: consent_receipt_dart
description: A library for working with Kantara Initiative Consent Receipts.
# version: 1.0.0
# homepage: https://www.example.com
authors:
  - Adaptant Labs <labs@adaptant.io>
  - Paul Mundt <paul.mundt@adaptant.io>

environment:
  sdk: '>=2.6.0-dev.7.0 <3.0.0'

dependencies:
  alpha2_countries: ^1.0.5
  validators: 2.0.0+1
  uuid: ^2.0.2

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
